

server:
  port: 8888
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
    uri-encoding: UTF-8
  servlet:
    context-path: '/'

# 开发期间模板引擎页面修改以后，要实时生效就要：1，禁用模板引擎的缓存。2，ctrl+f9：重新编译。
spring:
  thymeleaf:
    enable: true
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  resources:
    static-locations: classpath:/static/

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  rabbitmq:
      virtual-host: hymanhost
      username: hyman
      password: hyman
      addresses: 127.0.0.1:5672

# 指定全局日期解析的格式，默认是按照 / 的方式解析的。所以一般不用单独配置，应该直接在页面中说明。
#  mvc:
#    date-format: yyyy-MM-dd

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml

logging:
  path: classpath:/logback-spring.xml

# 所有的配置属性，参考文档：https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/htmlsingle/#common-application-properties。
