
server:
  port: 8888
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
    uri-encoding: UTF-8
  servlet:
    context-path: '/'

# 开发期间模板引擎页面修改以后，要实时生效就要：1，禁用模板引擎的缓存。2，ctrl+f9：重新编译。
spring:
  thymeleaf:
    enabled: true
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  resources:
    static-locations: classpath:/static/

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  rabbitmq:
      virtual-host: hymanhost
      username: hyman
      password: hyman
      addresses: 127.0.0.1:5672

#  rabbitmq:
#      username: guest
#      password: guest
#      host: 192.168.1.153

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

#   连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        min-idle: 8

#       连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        max-idle: 8

#   连接超时时间（毫秒）
    timeout: 0

  # 毫秒，秒，分，时，天
  cache:
    redis:
      timeToLive: 1h


# 指定全局日期解析的格式，默认是按照 / 的方式解析的。所以一般不用单独配置，应该直接在页面中说明。
#  mvc:
#    date-format: yyyy-MM-dd

# mybatis 自动配置了 sqlsessionfactory，并且它只对应于接口文件（接口上声明持久层注解），接口不能有实现类，就算有也不会执行。
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*.xml


# 使用监控功能，端口号加上 /monitor 才能访问相应的端点（默认是 /actuator），并且也只能访问添加过的端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,beans
      base-path: /monitor
  endpoint:
    health:
      show-details: always


logging:
  path: classpath:/logback-spring.xml

# 所有的配置属性，参考文档：https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/htmlsingle/#common-application-properties。
